[project]
name = "multilayer-notable-wiki-network"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "duckdb",
    "ipykernel==7.2.0",
    "jupyter==1.1.1",
    "numpy",
    "pandas",
    "psutil",
    "python-dotenv",
    "regex",
    "requests",
    "SPARQLWrapper",
    "tqdm",
    "urllib3",
]

[tool.uv]
package = false
